title: "CHI 2025 Workshop on Tools for Thought"
description: "A brief introduction to the upcoming workshop"
url: "https://ai-tools-for-thought.github.io/workshop/"
baseurl: ""
theme: minima # or another theme you prefer
markdown: kramdown
plugins:
  - jekyll-seo-tag